### ISSUE TITLE
Credenciales en Github

### ISSUE THREAD

**Issue by jselvi** [cyberwatcher17/cyberwatcher#1]
Esto no debería estar aquí. Mejor usar un gitignore para que el contenido de este fichero no se suba.

https://github.com/cyberwatcher17/cyberwatcher/blob/1e7d982124404897cfdc6aa8df0395689356cd30/config/conf.php#L5

Ahora que habéis publicado la contraseña, deberíais cambiarla.

**Comment by cyberwatcher17** [comment]
Gracias por el aviso.

Hemos creado el archivo gitignore.

Tambien hemos actualizado el repositorio. Todavia nos falta organizar mejor el código.

Un saludo.

**Comment by cybercamphackathon** [comment]
si ya está corregido, cerrar la issue

**Comment by cyberwatcher17** [comment]
Cierro la issue. Muchas gracias
