### ISSUE TITLE
Api Key Publica

### ISSUE THREAD

**Issue by alvarodh5** [cyberwatcher17/cyberwatcher#2]
Tenéis la API KEY de google maps publicada en el fichero: 

https://github.com/cyberwatcher17/cyberwatcher/blob/master/ajax/visualizarCiudades.php#L36

Tanto aquí como para resolver la issue https://github.com/cyberwatcher17/cyberwatcher/issues/1 recomendamos utilizar variables de entorno :)

**Comment by cyberwatcher17** [comment]
Muchas gracias por la recomendación :)

Lo hemos corregido.

Un saludo

**Comment by cybercamphackathon** [comment]
Cerrar la issue is ya está corregida

**Comment by cyberwatcher17** [comment]
Cierro la issue. Muchas gracias.
